from chainermnx.links.channel_parallel_convolution_2d import ChannelParallelConvolution2D
from chainermnx.links.channel_parallel_convolution_3d import ChannelParallelConvolution3D
from chainermnx.links.filter_parallel_convolution_2d import FilterParallelConvolution2D
from chainermnx.links.filter_parallel_convolution_3d import FilterParallelConvolution3D

from chainermnx.links.filter_parallel_linear import FilterParallelFC
from chainermnx.links.channel_parallel_linear import ChannelParallelFC

from chainermnx.links.spatial_convolution_2d import SpatialConvolution2D
# This takes care of 3D and such ie cosmoflow.
from chainermnx.links.spatial_convolution_nd import SpatialConvolution3D



